[package]
name = "game_client"
version = "1.0.0"
authors = ["AIM"]
edition = "2021"

[dependencies]
rand = "0.8"
image = "0.25"
tokio = { version = "1.40.0", features = ["full"] }
flo_draw = "0.3.1"
flo_canvas = "0.3.1"
play = "0.5.3"
